[package]
name = "aq-source-openmeteo"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aq-core.workspace = true
aq-http.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
